%bcond_without tests
%bcond_without weak_deps

%global debug_package %{nil}
%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^{{ installation_prefix }}/.*$
%global __requires_exclude_from ^{{ installation_prefix }}/.*$

Name:           {{ ros_pkgname }}
Version:        {{ version }}
Release:        {{ rpm_inc }}%{?dist}%{?release_suffix}
Summary:        ROS {{ pkgname }} package

License:        {{ license }}
    {% if homepage %}
URL:            {{ homepage }}
    {% endif %}
Source0:        %{name}-%{version}.tar.gz
    {% if no_arch %}
BuildArch:      noarch
    {% endif %}

    {% for p in depends %}
Requires:       {{ p }}
    {% endfor %}
    {% for p in build_depends %}
BuildRequires:  {{ p }}
    {% endfor %}
    {% for p in conflicts %}
Conflicts:      {{ p }}
    {% endfor %}
    {% for p in replaces %}
Obsoletes:      {{ p }}
    {% endfor %}
    {% for p in provides %}
Provides:       {{ p }}
    {% endfor %}

    {% if test_depends %}
%if 0%{?with_tests}
        {% for p in test_depends %}
BuildRequires:  {{ p }}
        {% endfor %}
%endif
    {% endif %}

    {% if supplements %}
%if 0%{?with_weak_deps}
        {% for p in supplements %}
Supplements:    {{ p }}
        {% endfor %}
%endif
    {% endif %}

%description
{{ description }}

%prep
%autosetup -p1

%build
{% block build %}{% endblock %}


%install
{% block install %}{% endblock %}


%files
{{ installation_prefix }}

%changelog
{% for log in changelogs -%}
* {{ log.date }} {{ log.mt_name }} <{{ log.mt_email }}> - {{ log.version }}
- Autogenerated by ros2rpm
{% endfor %}
